{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" . }}-cert
  namespace: istio-system
spec:
  secretName: {{ include "common.names.fullname" . }}-secret
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end}}